services:
  postgres:
    image: postgres
    container_name: crafty-db-test
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./server/.env.test

  node:
    container_name: crafty-server-test
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - ./server/.env.test