services:
  postgres:
    image: postgres
    container_name: crafty-db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - server/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: crafty-server
    restart: always
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - client/.env

  react:
    container_name: crafty-client
    build: ./client
    volumes:
      - react-volume:/var/www/html

  nginx_app:
    container_name: crafty-nginx
    restart: always
    build: ./infrastructure
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react-volume:
